export const DummyData = [
  {
    id: 1,
    default: true,
    personalDetails: {
      name: "Mahendra Balreddy",
      mobileNumber: "7780368926",
      email: "balreddymahendra7@gmail.com",
      city: "Nellore",
      state: "Andhra Pradesh",
      pincode: "524004",
    },
    summary: {
      description:
        "I am having 2+ years of Developing into ReactJS. Looking challenging role in an oraganization, where I can learn and use my technical skills to fulfill the company assignments, products and to deliver high performance applications as expected by the client.",
    },
    experience: [
      {
        companyName: "infibeam",
        designation: "React developer",
        startDate: "07/12/2021",
        end: "06/12/2022",
        projects: "gem, jit, BaB",
        rolesResponsibilites: [
          "Created UI from scrach using Html, Css, JavaScript.",
          "Created Reuseable components using React core priciples.",
          "Custom designs implemented using Material UI and Bootstrap",
          "Global state managed using Redux Toolkit.",
          "Implemented forms using Formik & Yup.",
        ],
      },
      {
        companyName: "0xytocin",
        designation: "React developer",
        startDate: "07/12/2021",
        end: "06/12/2022",
        projects: "goblinslayer, skyverse, tomo",
        rolesResponsibilites: [
          "Created UI from scrach using Html, Css, JavaScript.",
          "Created Reuseable components using React core priciples.",
          "Custom designs implemented using Material UI and Bootstrap",
          "Global state managed using Redux Toolkit.",
          "Implemented forms using Formik & Yup.",
        ],
      },
    ],

    education: [
      {
        collegeName: "Jawarharlal Nehru Technology Univerisity of Kakinada",
        courseName: "B.Tech",
        specification: "computer science",
        collegeLocation: "Banglore, Karnataka",
        startYear: "2017",
        endYear: "2021",
        percentage: "75%",
      },
      {
        collegeName: " Jagan's junior college",
        courseName: "12th",
        specification: "MPC",
        collegeLocation: "Banglore, Karnataka",
        startYear: "2017",
        endYear: "2021",
        percentage: "75%",
      },
      {
        collegeName: " Jagan's junior college",
        courseName: "10th",
        specification: "",
        collegeLocation: "Banglore, Karnataka",
        startYear: "2017",
        endYear: "2021",
        percentage: "75%",
      },
    ],
    skills: [
      { name: "Html", level: 4 },
      { name: "Css", level: 4 },
      { name: "JavaScript", level: 4 },
      { name: "ReactJS", level: 4 },
      { name: "Redux", level: 3 },
      { name: "Material UI", level: 3 },
    ],
    languages: [
      { name: "English", level: 4 },
      { name: "Telugu", level: 5 },
      { name: "Hindi", level: 2 },
    ],
    Intersets: ["Travelling", "Reading Books", "Watching You Tube"],
    Achievements: {},
    AcamedicProject: {},
    cerfication: {},
  },
  {
    id: 2,
    default: false,
    personalDetails: {
      name: "Aman Kumar",
      mobileNumber: "7780368926",
      email: "balreddymahendra7@gmail.com",
      city: "Nellore",
      state: "Andhra Pradesh",
      pincode: "524004",
    },
    summary: {
      description:
        "I am having 2+ years of Developing into ReactJS. Looking challenging role in an oraganization, where I can learn and use my technical skills to fulfill the company assignments, products and to deliver high performance applications as expected by the client.",
    },
    experience: [
      {
        companyName: "infibeam",
        designation: "React developer",
        startDate: "07/12/2021",
        end: "06/12/2022",
        projects: "gem, jit, BaB",
        rolesResponsibilites: [
          "Created UI from scrach using Html, Css, JavaScript.",
          "Created Reuseable components using React core priciples.",
          "Custom designs implemented using Material UI and Bootstrap",
          "Global state managed using Redux Toolkit.",
          "Implemented forms using Formik & Yup.",
        ],
      },
      {
        companyName: "0xytocin",
        designation: "React developer",
        startDate: "07/12/2021",
        end: "06/12/2022",
        projects: "goblinslayer, skyverse, tomo",
        rolesResponsibilites: [
          "Created UI from scrach using Html, Css, JavaScript.",
          "Created Reuseable components using React core priciples.",
          "Custom designs implemented using Material UI and Bootstrap",
          "Global state managed using Redux Toolkit.",
          "Implemented forms using Formik & Yup.",
        ],
      },
    ],

    education: [
      {
        collegeName: "Jawarharlal Nehru Technology Univerisity of Kakinada",
        courseName: "B.Tech",
        specification: "computer science",
        collegeLocation: "Banglore, Karnataka",
        startYear: "2017",
        endYear: "2021",
        percentage: "75%",
      },
      {
        collegeName: " Jagan's junior college",
        courseName: "12th",
        specification: "MPC",
        collegeLocation: "Banglore, Karnataka",
        startYear: "2017",
        endYear: "2021",
        percentage: "75%",
      },
      {
        collegeName: " Jagan's junior college",
        courseName: "10th",
        specification: "",
        collegeLocation: "Banglore, Karnataka",
        startYear: "2017",
        endYear: "2021",
        percentage: "75%",
      },
    ],
    skills: [
      { name: "Html", level: 4 },
      { name: "Css", level: 4 },
      { name: "JavaScript", level: 4 },
      { name: "ReactJS", level: 4 },
      { name: "Redux", level: 3 },
      { name: "Material UI", level: 3 },
    ],
    languages: [
      { name: "English", level: 4 },
      { name: "Telugu", level: 5 },
      { name: "Hindi", level: 2 },
    ],
    Intersets: ["Travelling", "Reading Books", "Watching You Tube"],
    Achievements: {},
    AcamedicProject: {},
    cerfication: {},
  },
];
