export const Templates = [{
    id:1,
    image:"https://www.my-resume-templates.com/wp-content/uploads/2019/07/57-sales-resume.jpg",
    name:"SimpleTemplate"
},
{
    id:2,
    image:"https://www.my-resume-templates.com/wp-content/uploads/2019/07/57-sales-resume.jpg",
    name:"SecondTemplate"
},
{
    id:3,
    image:"https://www.my-resume-templates.com/wp-content/uploads/2019/07/57-sales-resume.jpg",
    name:"ThirdTemplate"
},
{
    id:4,
    image:"https://www.my-resume-templates.com/wp-content/uploads/2019/07/57-sales-resume.jpg",
    name:"FourthTemplate"
},
{
    id:5,
    image:"https://www.my-resume-templates.com/wp-content/uploads/2019/07/57-sales-resume.jpg",
    name:"FifthTemplate"
}]